### ISSUE TITLE
embeddings missing

### ISSUE THREAD

**Issue by vipinkumar7** [sekharvth/symptom-disease#1]
Hi can you share these embeddings    
data/glove.6B.50d.txt

**Comment by zabir-nabil** [comment]
It's a big file, you can download it from here https://www.kaggle.com/watts2/glove6b50dtxt

**Comment by mocoley** [comment]
> Hi can you share these embeddings
> data/glove.6B.50d.txt

Were you able to figure out how to run this code?

**Comment by sekharvth** [comment]
Hi,
Once you've downloaded the embeddings, just replace the '/data/glove..' file path with the path to where you've downloaded it to.
Closing this for now, reopen if necessary :)
