### ISSUE TITLE
Disease_Symptoms.xlsx

### ISSUE THREAD

**Issue by pythonmaster93** [sekharvth/symptom-disease#2]
I ran your code but I am getting an error saying that it cannot find the file **_Disease_Symptoms.xlsx_** I did not see this file in your code, is this something I have to create?

**Comment by sekharvth** [comment]
Hi there, 
The data was obtained from here: http://people.dbmi.columbia.edu/~friedma/Projects/DiseaseSymptomKB/index.html

After some basic preprocessing, the same file was changed to the said filename. So yes, it is ultimately something you create out of the above link.
